# Generated by Django 3.2.5 on 2021-12-10 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0002_alter_mindpalacenode_body_type'),
        ('palace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermindpalace',
            name='root',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='mind_palace', to='node.mindpalacenode'),
        ),
    ]
