# Generated by Django 3.2.5 on 2021-07-19 20:22

import datetime
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('node', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLearningSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'active'), ('finished', 'finished')], default='active', max_length=100)),
                ('strategy_name', models.CharField(choices=[('sm2', 'supermemo_2')], default='sm2', max_length=1000)),
                ('queue', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('repeated_nodes', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('start_datetime', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('end_datetime', models.DateTimeField(default=None, null=True)),
                ('last_repetition_datetime', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='node.mindpalacenode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
