# Generated by Django 4.0.5 on 2022-06-18 13:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('node', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeLearningStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('middle', 'middle'), ('rookie', 'rookie'), ('senior', 'senior')], default='rookie', max_length=100)),
                ('interval', models.IntegerField(default=0)),
                ('repetitions', models.BigIntegerField(default=0)),
                ('views', models.BigIntegerField(default=0)),
                ('positive_repetitions_in_row', models.BigIntegerField(default=0)),
                ('easiness', models.DecimalField(decimal_places=2, default=2.6, max_digits=4)),
                ('average_rate', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('last_repetition', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('next_repetition', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('last_view', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_statistics', to='node.palacenode')),
            ],
        ),
    ]
