# Generated by Django 3.2.5 on 2021-07-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_alter_nodelearningstatistics_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodelearningstatistics',
            name='views',
            field=models.BigIntegerField(default=0),
        ),
    ]
