# Generated by Django 3.2.5 on 2022-05-17 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_nodelearningstatistics_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodelearningstatistics',
            name='last_view',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
    ]
