# Generated by Django 3.2.5 on 2021-07-19 20:22

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NodeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='MindPalaceNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Name')),
                ('title', models.TextField(blank=True, default='', null=True, verbose_name='Title')),
                ('audio', models.FileField(blank=True, null=True, upload_to='audios/', verbose_name='Audio')),
                ('body_type', models.CharField(choices=[('chess', 'CHESS'), ('code', 'CODE'), ('microexpression', 'MICROEXPRESSION'), ('text', 'TEXT'), ('translation', 'TRANSLATION')], default='text', max_length=50)),
                ('body', models.JSONField(default=dict, verbose_name='Body')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='node.mindpalacenode', verbose_name='Parent')),
                ('tags', models.ManyToManyField(to='node.NodeTag', verbose_name='Tags')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
