# Generated by Django 3.2.5 on 2021-07-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mindpalacenode',
            name='body_type',
            field=models.CharField(choices=[('biography', 'BIOGRAPHY'), ('chess', 'CHESS'), ('code', 'CODE'), ('historical_event', 'HISTORICAL_EVENT'), ('microexpression', 'MICROEXPRESSION'), ('text', 'TEXT'), ('translation', 'TRANSLATION')], default='text', max_length=50),
        ),
    ]
