# Generated by Django 3.2.5 on 2021-12-10 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0002_alter_mindpalacenode_body_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MindPalaceNodeMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('image', 'IMAGE'), ('not_set', 'NOT_SET'), ('youtube', 'YOUTUBE')], default='not_set', max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(default=None, null=True)),
                ('image', models.ImageField(upload_to='node_media/')),
                ('media_config', models.JSONField(default=dict)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='node.mindpalacenode')),
            ],
        ),
    ]
