# Generated by Django 3.2.5 on 2021-12-12 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0003_mindpalacenodemedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mindpalacenode',
            name='body_type',
            field=models.CharField(choices=[('chess', 'CHESS'), ('code', 'CODE'), ('text', 'TEXT')], default='text', max_length=50),
        ),
        migrations.AlterField(
            model_name='mindpalacenodemedia',
            name='title',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
