# Generated by Django 3.2.5 on 2022-01-09 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0005_rename_media_config_mindpalacenodemedia_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mindpalacenode',
            name='body_type',
            field=models.CharField(choices=[('chess', 'CHESS'), ('code', 'CODE'), ('text', 'TEXT'), ('translation', 'TRANSLATION')], default='text', max_length=50),
        ),
    ]
