# Generated by Django 3.2.5 on 2022-05-17 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0006_alter_mindpalacenode_body_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mindpalacenode',
            name='body',
        ),
        migrations.RemoveField(
            model_name='mindpalacenode',
            name='body_type',
        ),
        migrations.CreateModel(
            name='NodeBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('chess', 'CHESS'), ('code', 'CODE'), ('text', 'TEXT'), ('translation', 'TRANSLATION')], default='text', max_length=50)),
                ('meta', models.JSONField(default=dict)),
                ('data', models.JSONField(default=dict)),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='node.mindpalacenode')),
            ],
        ),
    ]
