# Generated by Django 3.2.5 on 2022-05-17 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('node', '0007_auto_20220517_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='mindpalacenode',
            name='owner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to=settings.AUTH_USER_MODEL),
        ),
    ]
