# Generated by Django 3.2.5 on 2022-01-09 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_rename_end_datetime_userlearningsession_finish_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlearningsession',
            name='average_rating',
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='userlearningsession',
            name='total_repetitions',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
