# Generated by Django 3.2.5 on 2022-01-09 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0003_auto_20220109_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlearningsession',
            name='average_rating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
