# Generated by Django 3.2.5 on 2022-01-09 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0004_alter_userlearningsession_average_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlearningsession',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
    ]
